default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: illae-dev

test:
  <<: *default
  database: illae-test

production:
  <<: *default
  database: illae
