# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ad503c7729afb291e8f37e89c11c431f730b72a88d523a9ca579e314947ec80036cb69c6c1e54f7e447c0b89ae770cb2bbf97557e6178796151d8f19a404321

test:
  secret_key_base: dc2352f09be8ff5134eea355d85300ad4ab1a36670d971b6ca537cc5b2c315d62ff22568d788db1f58cdec9c511ce0d86e5d8e3cf63618111f411d8fd2d01587

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
